# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyNAT.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PyNAT(object):
    def setupUi(self, PyNAT):
        PyNAT.setObjectName("PyNAT")
        PyNAT.resize(330, 237)
        PyNAT.setToolTip("")
        self.External_input = QtWidgets.QLabel(PyNAT)
        self.External_input.setGeometry(QtCore.QRect(90, 90, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.External_input.setFont(font)
        self.External_input.setText("")
        self.External_input.setObjectName("External_input")
        self.CheckButton = QtWidgets.QPushButton(PyNAT)
        self.CheckButton.setGeometry(QtCore.QRect(160, 200, 75, 23))
        self.CheckButton.setIconSize(QtCore.QSize(18, 18))
        self.CheckButton.setCheckable(True)
        self.CheckButton.setChecked(False)
        self.CheckButton.setAutoRepeat(False)
        self.CheckButton.setAutoExclusive(False)
        self.CheckButton.setObjectName("CheckButton")
        self.Internal_input = QtWidgets.QLabel(PyNAT)
        self.Internal_input.setGeometry(QtCore.QRect(90, 50, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Internal_input.setFont(font)
        self.Internal_input.setText("")
        self.Internal_input.setObjectName("Internal_input")
        self.NAT_input = QtWidgets.QLabel(PyNAT)
        self.NAT_input.setGeometry(QtCore.QRect(90, 10, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.NAT_input.setFont(font)
        self.NAT_input.setText("")
        self.NAT_input.setObjectName("NAT_input")
        self.Internal_text = QtWidgets.QLabel(PyNAT)
        self.Internal_text.setGeometry(QtCore.QRect(10, 50, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Internal_text.setFont(font)
        self.Internal_text.setObjectName("Internal_text")
        self.External_text = QtWidgets.QLabel(PyNAT)
        self.External_text.setGeometry(QtCore.QRect(10, 90, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.External_text.setFont(font)
        self.External_text.setObjectName("External_text")
        self.ShutdownButton = QtWidgets.QPushButton(PyNAT)
        self.ShutdownButton.setGeometry(QtCore.QRect(250, 200, 75, 23))
        self.ShutdownButton.setObjectName("ShutdownButton")
        self.NAT_text = QtWidgets.QLabel(PyNAT)
        self.NAT_text.setGeometry(QtCore.QRect(10, 10, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.NAT_text.setFont(font)
        self.NAT_text.setObjectName("NAT_text")
        self.progressBar = QtWidgets.QProgressBar(PyNAT)
        self.progressBar.setGeometry(QtCore.QRect(10, 160, 311, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.SettingButton = QtWidgets.QPushButton(PyNAT)
        self.SettingButton.setGeometry(QtCore.QRect(70, 200, 75, 23))
        self.SettingButton.setIconSize(QtCore.QSize(18, 18))
        self.SettingButton.setCheckable(True)
        self.SettingButton.setChecked(False)
        self.SettingButton.setAutoRepeat(False)
        self.SettingButton.setAutoExclusive(False)
        self.SettingButton.setObjectName("SettingButton")

        self.retranslateUi(PyNAT)
        QtCore.QMetaObject.connectSlotsByName(PyNAT)

    def retranslateUi(self, PyNAT):
        _translate = QtCore.QCoreApplication.translate
        PyNAT.setWindowTitle(_translate("PyNAT", "PyNAT"))
        self.CheckButton.setText(_translate("PyNAT", "檢測"))
        self.NAT_input.setToolTip(_translate("PyNAT", "<html><head/><body><p><span style=\" font-family:\'Tahoma,Microsoft Yahei,Simsun\'; font-size:14px; font-weight:696; color:#444444; background-color:#ffffff;\">NAT1 </span><span style=\" font-family:\'Tahoma,Microsoft Yahei,Simsun\'; font-size:14px; color:#444444; background-color:#ffffff;\">→ </span><span style=\" font-family:\'Tahoma,Microsoft Yahei,Simsun\'; font-size:14px; font-weight:696; color:#ff0000; background-color:#ffffff;\">Full Cone</span><span style=\" font-family:\'Tahoma,Microsoft Yahei,Simsun\'; font-size:14px; color:#444444; background-color:#ffffff;\"> NAT </span></p><p><span style=\" font-family:\'Tahoma,Microsoft Yahei,Simsun\'; font-size:14px; font-weight:696; color:#444444; background-color:#ffffff;\">NAT2 </span><span style=\" font-family:\'Tahoma,Microsoft Yahei,Simsun\'; font-size:14px; color:#444444; background-color:#ffffff;\">→ </span><span style=\" font-family:\'Tahoma,Microsoft Yahei,Simsun\'; font-size:14px; font-weight:696; color:#444444; background-color:#ffffff;\">Address-</span><span style=\" font-family:\'Tahoma,Microsoft Yahei,Simsun\'; font-size:14px; font-weight:696; color:#ff0000; background-color:#ffffff;\">Restricted Cone</span><span style=\" font-family:\'Tahoma,Microsoft Yahei,Simsun\'; font-size:14px; color:#444444; background-color:#ffffff;\"> NAT</span></p><p><span style=\" font-family:\'Tahoma,Microsoft Yahei,Simsun\'; font-size:14px; font-weight:696; color:#444444; background-color:#ffffff;\">NAT3 </span><span style=\" font-family:\'Tahoma,Microsoft Yahei,Simsun\'; font-size:14px; color:#444444; background-color:#ffffff;\">→ </span><span style=\" font-family:\'Tahoma,Microsoft Yahei,Simsun\'; font-size:14px; font-weight:696; color:#ff0000; background-color:#ffffff;\">Port-Restricted Cone</span><span style=\" font-family:\'Tahoma,Microsoft Yahei,Simsun\'; font-size:14px; color:#444444; background-color:#ffffff;\"> NAT </span></p><p><span style=\" font-family:\'Tahoma,Microsoft Yahei,Simsun\'; font-size:14px; font-weight:696; color:#444444; background-color:#ffffff;\">NAT4 </span><span style=\" font-family:\'Tahoma,Microsoft Yahei,Simsun\'; font-size:14px; color:#444444; background-color:#ffffff;\">→ </span><span style=\" font-family:\'Tahoma,Microsoft Yahei,Simsun\'; font-size:14px; font-weight:696; color:#ff0000; background-color:#ffffff;\">Symmetric</span><span style=\" font-family:\'Tahoma,Microsoft Yahei,Simsun\'; font-size:14px; color:#444444; background-color:#ffffff;\"> NAT</span></p></body></html>"))
        self.Internal_text.setText(_translate("PyNAT", "內部地址："))
        self.External_text.setText(_translate("PyNAT", "外部地址："))
        self.ShutdownButton.setText(_translate("PyNAT", "關閉"))
        self.NAT_text.setText(_translate("PyNAT", "NAT模式："))
        self.SettingButton.setText(_translate("PyNAT", "設定"))

